# Generated by Django 4.0.2 on 2022-02-20 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history_rename_hero_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='embed_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='embed_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
